# Generated by Django 4.1.1 on 2022-10-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='new_price',
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='name',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
