# Generated by Django 4.1.1 on 2022-10-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_price_product_new_price_product_old_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='name',
            new_name='how_much',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='slug',
        ),
    ]
