# Generated by Django 4.1.1 on 2022-10-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_name_quantity_how_much_remove_quantity_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdescription',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
        migrations.AddField(
            model_name='productdescription',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
    ]
