# Generated by Django 4.1.1 on 2022-10-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_picture_remove_product_photo_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='multi_shop/static/default_picture', upload_to=''),
        ),
    ]
