# Generated by Django 4.1.1 on 2022-10-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_customer_product_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customer',
            field=models.ManyToManyField(blank=True, to='product.customer'),
        ),
    ]
