# Generated by Django 4.1.1 on 2022-10-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customer',
            field=models.ManyToManyField(blank=True, related_name='clients', to='product.customer'),
        ),
    ]
